### ISSUE TITLE
On visual expert

### ISSUE THREAD

**Issue by John-Ge** [NVlabs/EAGLE#1]
Hello, very nice work. After reading your paper, I noticed that in Table. 5, CLIP+ConvNeXt has an average performance of  667, while combining more visual expert results in an average performance of 666 in Table. 6. Does this mean that combing two visual encoders is enough? Thank you!

**Comment by Chrisding** [comment]
Hi John-Ge, thanks for the question!
It is because Table. 6 contains one more benchmark GQA, which is not calculated in Table. 5.
Sorry for the confusion! Hope this helps.
