### ISSUE TITLE
ValueError: Unable to create tensor, you should probably activate padding with 'padding=True' to have batched tensors with the same length

### ISSUE THREAD

**Issue by thebazshah** [NVlabs/EAGLE#11]
Hi, I am getting this issue. I am running it on following system. I followed the instructions given in README.

- Ubuntu 24.04
- Intel Core i7
- 16GB RAM
- Anaconda
- Pytorch CPU Only version (I don't have a Nvidia GPU)

Any idea about how to solve this issue?

![Screenshot from 2024-09-08 07-58-00](https://github.com/user-attachments/assets/4bb94303-9f63-499b-b32f-579465532a6b)

**Comment by flyinglynx** [comment]
Sorry, we currently do not support CPU-based inference or training. I plan to explore additional optimizations and inference frameworks for LLMs when I have more time. Apologies for the inconvenience. Feel free to try our online demo.
